version: '3.7'

networks:
  node-streams:


services:
  node-streams:
    build: .
    container_name: node-streams
    # entrypoint: sh .docker/entrypoint.sh
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - .:/usr/node-streams/app
    networks:
      - node-streams
